project:
  type: website
  output-dir: docs

website:
  site-url: "https://sorenqwer.github.io/my-notes-site/"
  title: "Margins of Rationality"
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: notes/index.qmd
        text: Notes
      - href: foundations/index.qmd
        text: Foundations
      - href: pdfs/index.qmd
        text: PDFs
      - href: criminology/index.qmd
        text: Criminology
      - href: psychology/index.qmd
        text: Psychology

format:
  html:
    mermaid: {}
    css: styles.css
    include-after-body:
      - _includes/diagram-zoom.html
    toc: false
    page-layout: full
    title-block-style: plain

bibliography: references.bib
